#!/usr/bin/env bash
# Installs fail2ban to stop SSH password-guessing bots: any IP that gets the
# root password wrong 5 times within 10 minutes is banned for an hour, and
# repeat offenders get banned for longer each time (up to a week).
#
#   sudo ./scripts/fail2ban.sh            install / update
#   sudo ./scripts/fail2ban.sh --status   show banned IPs
#   sudo ./scripts/fail2ban.sh --unban 1.2.3.4
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "Please run as root:  sudo ./scripts/fail2ban.sh" >&2
  exit 1
fi

case "${1:-}" in
  --status) fail2ban-client status sshd; exit 0 ;;
  --unban)  fail2ban-client set sshd unbanip "${2:?Usage: $0 --unban <ip>}"; exit 0 ;;
esac

echo "==> Installing fail2ban"
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq fail2ban python3-systemd >/dev/null

# Never ban the IP you're connected from right now.
me="${SSH_CLIENT%% *}"

# Ubuntu images without rsyslog only log SSH to the systemd journal.
if [[ -f /var/log/auth.log ]]; then backend=auto; else backend=systemd; fi

cat > /etc/fail2ban/jail.local <<JAIL
# Generated by scripts/fail2ban.sh
[DEFAULT]
ignoreip = 127.0.0.1/8 ::1 ${me}
bantime = 1h
bantime.increment = true
bantime.maxtime = 1w
findtime = 10m
maxretry = 5

[sshd]
enabled = true
backend = ${backend}
JAIL

systemctl enable fail2ban >/dev/null 2>&1
systemctl restart fail2ban
sleep 3

echo
fail2ban-client status sshd
echo
echo "fail2ban is protecting SSH."
[[ -n "$me" ]] && echo "Your current IP (${me}) will never be banned."
