#!/usr/bin/env bash
# Installs a small set of QoL plugins from the TShockPlugin collection
# (github.com/UnrealMultiple/TShockPlugin), gives everyone permission to use
# them, and restarts the server. Safe to re-run — it replaces what it installed.
#
#   Back             /back           teleport to where you last died
#   TeleportRequest  /tpa <player>   ask to teleport to a friend (/atp accept, /dtp deny)
#   TownNPCHomes     /npchome        send town NPCs back to their houses
#   BanNpc           /bm add <id>    stop an NPC from spawning (admins; /bm list, /bm del <id>)
#   AdditionalPylons                 place up to 2 of each pylon type
#                                    (limits in data/tshock/AdditionalPylons*.json)
#
# To remove all plugins:  sudo ./scripts/plugins.sh --remove
set -euo pipefail

cd "$(dirname "$0")/.."

PLUGINS=(Back TeleportRequest TownNPCHomes BanNpc AdditionalPylons)
LIBS=(LazyAPI linq2db)   # shared libraries several of these depend on
BUNDLE_URL="https://github.com/UnrealMultiple/TShockPlugin/releases/download/V1.0.0.0/Plugins.zip"

# Vanilla actions guests can't do by default in TShock, plus the plugin commands.
PERMS=(
  tshock.tp.wormhole tshock.tp.pylon tshock.tp.tppotion tshock.tp.rod
  tshock.tp.magicconch tshock.tp.demonconch tshock.npc.summonboss tshock.npc.spawnpets
  tshock.npc.startinvasion tshock.npc.startdd2 tshock.world.movenpc tshock.world.paint
  tshock.world.worldupgrades tshock.warp tshock.whisper
  back tprequest.tpat tprequest.gettpr tprequest.tpauto
  AdditionalPylons
)

if [[ $EUID -ne 0 ]]; then
  echo "Please run as root:  sudo ./scripts/plugins.sh" >&2
  exit 1
fi

step() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }

step "Backing up first"
./scripts/backup.sh

mkdir -p data/plugins data/plugin-libs
rm -f data/plugins/*.dll data/plugin-libs/*.dll

if [[ "${1:-}" == "--remove" ]]; then
  rm -f docker-compose.override.yml
  step "Restarting without plugins"
  docker compose up -d --force-recreate
  echo "All plugins removed."
  exit 0
fi

step "Downloading plugins"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
curl -fsSL -o "$tmp/Plugins.zip" "$BUNDLE_URL"
python3 - "$tmp/Plugins.zip" "${PLUGINS[*]}" "${LIBS[*]}" <<'PY'
import sys, zipfile, pathlib
bundle, plugins, libs = sys.argv[1], sys.argv[2].split(), sys.argv[3].split()
with zipfile.ZipFile(bundle) as z:
    for names, dest in ((plugins, "data/plugins"), (libs, "data/plugin-libs")):
        for n in names:
            pathlib.Path(dest, f"{n}.dll").write_bytes(z.read(f"Plugins/{n}.dll"))
            print(f"  {n}")
PY

# TShock only resolves plugin dependencies from its own ServerPlugins folder,
# so the shared libraries are mounted there individually.
cat > docker-compose.override.yml <<'YML'
# Generated by scripts/plugins.sh — do not edit by hand.
services:
  terraria:
    volumes:
      - ./data/plugin-libs/LazyAPI.dll:/server/ServerPlugins/LazyAPI.dll:ro
      - ./data/plugin-libs/linq2db.dll:/server/ServerPlugins/linq2db.dll:ro
YML

step "Stopping the server (the world is saved)"
docker compose stop

step "Granting permissions to all players"
python3 - "${PERMS[@]}" <<'PY'
import sys, sqlite3
db = sqlite3.connect("data/tshock/tshock.sqlite")
row = db.execute("SELECT Commands FROM GroupList WHERE GroupName='guest'").fetchone()
if row is None:
    sys.exit("No 'guest' group found — has the server been started at least once?")
perms = [p for p in (row[0] or "").split(",") if p]
perms += [p for p in sys.argv[1:] if p not in perms]
db.execute("UPDATE GroupList SET Commands=? WHERE GroupName='guest'", (",".join(perms),))
db.commit()
print("  guest (and every group that inherits from it) updated.")
PY

step "Starting the server"
docker compose up -d --force-recreate
sleep 15
docker compose logs --tail 60 | grep -iE "plugin|error|exception" || true

echo
echo "────────────────────────────────────────────"
echo "  Plugins installed. New commands for everyone:"
echo "    /back            go back to where you died"
echo "    /tpa <player>    ask to teleport to someone"
echo "    /atp  /dtp       accept / deny a request"
echo "    /npchome         send NPCs back home"
echo "  Pylons:  everyone can place up to 2 of each type"
echo "  Admins:  /bm add <npc id>   block an NPC from spawning"
echo "────────────────────────────────────────────"
